/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 543f992083f7639592591242de0b7088)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyDurableObject";
	}
	interface Env {
		MY_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").MyDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
