/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: d101299e053c3803a568b604b9888c5d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyDurableObject" | "MyContainerObject";
	}
	interface Env {
		MY_CONTAINER_OBJECT: DurableObjectNamespace<import("./src/index").MyContainerObject>;
		MY_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").MyDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
